// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARlA4kDs3dZIGLkgEkxqSoqsgSrEDJy9o',
    appId: '1:642708383585:web:8e74b70b9531636c9e4720',
    messagingSenderId: '642708383585',
    projectId: 'evently-sat-c17',
    authDomain: 'evently-sat-c17.firebaseapp.com',
    storageBucket: 'evently-sat-c17.firebasestorage.app',
    measurementId: 'G-MHC1HLFC9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEn9Macyl_RR6syAYBXij8YiM5LJBGfuA',
    appId: '1:642708383585:android:ffda83c0e4e6c08a9e4720',
    messagingSenderId: '642708383585',
    projectId: 'evently-sat-c17',
    storageBucket: 'evently-sat-c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeJmdiyG-LDVvMwnAUPnhBQdHS1G7BA-Y',
    appId: '1:642708383585:ios:a8fad911232a03ec9e4720',
    messagingSenderId: '642708383585',
    projectId: 'evently-sat-c17',
    storageBucket: 'evently-sat-c17.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeJmdiyG-LDVvMwnAUPnhBQdHS1G7BA-Y',
    appId: '1:642708383585:ios:a8fad911232a03ec9e4720',
    messagingSenderId: '642708383585',
    projectId: 'evently-sat-c17',
    storageBucket: 'evently-sat-c17.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );
}
